### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by rscm** [flathub/net.epson.epsonscan2#1]
Flatpak: 1.12.7
epsonscan2 version: 6.6.42.0

OS: Fedora 36 Silverblue

```
rpm-ostree status
State: idle
Deployments:
● fedora:fedora/36/x86_64/silverblue
                  Version: 36.20221019.0 (2022-10-19T10:01:39Z)
               BaseCommit: 6688dcc4c096e0bbf379ef1618a16e12cabe9db6353961966d4d084b4e715bd5
             GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
      RemovedBasePackages: firefox 105.0.2-1.fc36 gnome-software gnome-software-rpm-ostree 42.4-2.fc36
          LayeredPackages: akmod-nvidia gnome-tweaks starship steam-devices tailscale terminator xboxdrv xorg-x11-drv-nvidia
            LocalPackages: rpmfusion-free-release-36-1.noarch rpmfusion-nonfree-release-36-1.noarch teamviewer-15.34.4-0.x86_64
```

Log:
```
$ flatpak run net.epson.epsonscan2 
Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
Gtk-Message: 19:29:50.934: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:29:50.934: Failed to load module "canberra-gtk-module"
Qt: Session management error: Could not open network socket
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
/usr/bin/which: no avahi-browse in (/app/bin:/usr/bin)
/usr/include/c++/12.1.0/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = SDIDeviceInfo; _Alloc = std::allocator<SDIDeviceInfo>; reference = SDIDeviceInfo&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
```
